### ISSUE TITLE
Why multiple terms for DataNode?

### ISSUE THREAD

**Issue by ariutta** [wikipathways/WpVocabularies#14]
Why do we have three vocabulary entries for DataNode?

1. [wpTypes:Datanode](https://vocabularies.wikipathways.org/wpTypes)
2. [gpml:DataNode](https://vocabularies.wikipathways.org/gpml#DataNode)
3. [wp:DataNode](https://vocabularies.wikipathways.org/wp#DataNode)

Can't we define it just one time to keep things simple?

**Comment by AlexanderPico** [comment]
wp and gpml are necessary, because they are conceptually different. The gpml vocab is generic, capturing the structure and layout, while the wp vocab is specific to our usage at WikiPathways, capturing the biology. This section of the paper explains in more detail: 
http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004989#sec002


@RyAMiller started the wpTypes vocab, so perhaps he can comment on its use cases....

**Comment by mkutmon** [comment]
Quick comment about the WpTypes vocabulary. A while ago, we discussed the idea to set up a vocabulary describing valid dataNode and interaction (arrowhead) values that can be shared between PV and pvjs. This was set up but I am not sure about its status. I don't think it's used anywhere at the moment.
